version: "3"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    networks:
      - stellar
    environment:
      - POSTGRES_PASSWORD=password
  stellar-core:
    image: quay.io/evilmartians/docker-stellar-core:latest
    environment:
      - STELLAR_CORE_DATABASE_URL=postgresql://dbname=stellarcore host=postgres user=postgres password=password
      - STELLAR_CORE_HISTORY_ARCHIVES=cache,gcloud,gs://stellar-core-testnet-history-cache/
    networks:
      - stellar
    volumes:
      - ./stellar-core-testnet-example.cfg:/etc/stellar/stellar-core.cfg
      - ./boto-example.cfg:/etc/boto.cfg
      - ./gcloud-service-account-key.json:/etc/gcloud-service-account.json
      - ./data:/var/lib/stellar/
      - ./logs:/var/log/stellar
    depends_on:
      - postgres

networks:
  stellar:
